package com.robertx22.mmorpg;

import net.minecraft.world.WorldServer;
import net.minecraftforge.common.DimensionManager;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.capabilities.CapabilityManager;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.*;
import net.minecraftforge.fml.common.registry.GameRegistry;

import java.util.Arrays;

import com.robertx22.capability.EntityData;
import com.robertx22.capability.EntityData.DefaultImpl;
import com.robertx22.capability.EntityData.IData;
import com.robertx22.capability.EntityData.Storage;
import com.robertx22.commands.GiveGear;
import com.robertx22.commands.GiveSocket;
import com.robertx22.commands.SetLevel;
import com.robertx22.customitems.MyItems;
import com.robertx22.customitems.NewItemCreator;
import com.robertx22.onevent.OnLogin;
import com.robertx22.onevent.Combat.*;
import com.robertx22.onevent.Gearupgrade.OnAnvilRepair;
import com.robertx22.onevent.Gearupgrade.OnAnvilSetLevel;
import com.robertx22.onevent.Gearupgrade.OnAnvilSocket;
import com.robertx22.onevent.Gearupgrade.OnAnvilUpgrade;
import com.robertx22.onevent.Item.OnPickup;
import com.robertx22.onevent.Item.OnTooltip;
import com.robertx22.onevent.Loot.OnMobDeathDrops;
import com.robertx22.onevent.Loot.OnMobDeathGetExp;
import com.robertx22.onevent.Ontick.OnTickRegen;
import com.robertx22.onevent.Ontick.OnTickRenderItemNames;
import com.robertx22.oregen.OreGen;
import com.robertx22.player.PlayerData;

@Mod(modid = Ref.MODID, version = Ref.VERSION, name = Ref.NAME)
public class Main {

    @EventHandler
    public void start(FMLServerStartingEvent event) {
        event.registerServerCommand(new GiveGear());
        event.registerServerCommand(new GiveSocket());
        event.registerServerCommand(new SetLevel());

    }

    @EventHandler
    public static void onWorldLoad(FMLServerStartedEvent event) {
        WorldServer world = DimensionManager.getWorld(0); // default world

        world.getGameRules().setOrCreateGameRule("mobGriefing", "false");
        world.getGameRules().setOrCreateGameRule("keepInventory", "true");
        world.getGameRules().setOrCreateGameRule("naturalRegeneration", "false");

    }

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {

        ModMetadata modMeta = event.getModMetadata();
        modMeta.name = Ref.NAME;
        modMeta.version = Ref.VERSION;
        modMeta.authorList = Arrays.asList(new String[]{"robertx22"});
        modMeta.autogenerated = false;
        modMeta.description = Ref.DESC;

        CapabilityManager.INSTANCE.register(IData.class, new Storage(), DefaultImpl.class);

        MinecraftForge.EVENT_BUS.register(new EntityData());
        MinecraftForge.EVENT_BUS.register(new EntityData.EventHandler());
        MinecraftForge.EVENT_BUS.register(new OnMobDeathDrops());
        MinecraftForge.EVENT_BUS.register(new ModConfig());
        MinecraftForge.EVENT_BUS.register(new OnTooltip());
        MinecraftForge.EVENT_BUS.register(new OnLogin());
        MinecraftForge.EVENT_BUS.register(new OnPlayerAttack());
        MinecraftForge.EVENT_BUS.register(new PlayerData());
        MinecraftForge.EVENT_BUS.register(new OnMobSpawn());
        MinecraftForge.EVENT_BUS.register(new OnMobAttack());
        MinecraftForge.EVENT_BUS.register(new OnTickRegen());
        MinecraftForge.EVENT_BUS.register(new OnBurnStop());
        MinecraftForge.EVENT_BUS.register(new OnMobDeathGetExp());
        MinecraftForge.EVENT_BUS.register(new OnMobsAttackEachOther());
        MinecraftForge.EVENT_BUS.register(new OnAnvilSocket());
        MinecraftForge.EVENT_BUS.register(new OnAnvilUpgrade());
        MinecraftForge.EVENT_BUS.register(new OnAnvilSetLevel());
        MinecraftForge.EVENT_BUS.register(new OnPickup());
        MinecraftForge.EVENT_BUS.register(new OnTickRenderItemNames());
        MinecraftForge.EVENT_BUS.register(new OnAnvilRepair());

        NewItemCreator.createCustomItems();

    }

    @EventHandler
    public void init(FMLInitializationEvent event) {

        GameRegistry.registerWorldGenerator(new OreGen(MyItems.magic_ore_block, 7, 10, 50, 7), 0);
        GameRegistry.registerWorldGenerator(new OreGen(MyItems.rare_ore_block, 6, 10, 40, 5), 0);
        GameRegistry.registerWorldGenerator(new OreGen(MyItems.epic_ore_block, 5, 10, 35, 3), 0);
        GameRegistry.registerWorldGenerator(new OreGen(MyItems.legendary_ore_block, 5, 10, 30, 2), 0);
        GameRegistry.registerWorldGenerator(new OreGen(MyItems.mythical_ore_block, 4, 10, 30, 1), 0);

    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent event) {

    }

}
